export const SET_TICKER_PRICE_API_VALUE = 'SET_TICKER_PRICE_API_VALUE';
export const GET_TICKER_PRICE_API_SUCCESS = 'GET_TICKER_PRICE_API_SUCCESS';
export const GET_TICKER_PRICE_API_ERROR = 'GET_TICKER_PRICE_API_ERROR';